---
- name: Install the required dependency packages
  dnf:
    name: "{{ item }}"
    state: present
  loop:
    - java-17-amazon-corretto
    - git
    - wget
    - gnupg
    - yum-utils
    - device-mapper-persistent-data
    - lvm2

- name: Add Jenkins repository
  copy:
    dest: /etc/yum.repos.d/jenkins.repo
    content: |
      [jenkins]
      name=Jenkins
      baseurl=https://pkg.jenkins.io/redhat-stable/
      gpgcheck=1
      gpgkey=https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key
      enabled=1

- name: Clear DNF cache
  command: dnf clean all

- name: Make sure DNF cache is updated
  command: dnf makecache

- name: Install Jenkins
  dnf:
    name: jenkins
    state: present
  register: jenkins_install_result

- name: Check if Jenkins was installed successfully
  debug:
    msg: "Jenkins installation result: {{ jenkins_install_result }}"
  when: jenkins_install_result is changed

- name: Wait for a few seconds for the system to catch up
  pause:
    seconds: 5

- name: Start Jenkins service
  service:
    name: jenkins
    state: started
    enabled: true
  register: jenkins_service_start
  failed_when: jenkins_service_start is failed

- name: Check Jenkins service status
  command: systemctl status jenkins
  register: jenkins_service_status
  ignore_errors: true

- name: Display Jenkins service status
  debug:
    msg: "{{ jenkins_service_status.stdout }}"

- name: Fetch Jenkins initial admin password
  shell: cat /var/lib/jenkins/secrets/initialAdminPassword
  changed_when: false
  register: jenkins_initial_password
  ignore_errors: true  # Ignore errors if the file does not exist

- name: Display Jenkins initial admin password
  debug:
    msg: "Jenkins initial admin password: {{ jenkins_initial_password.stdout }}"
  when: jenkins_initial_password.stdout is defined

