- name: Download kubectl binary
  get_url:
    url:  curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
    dest: /usr/local/bin/kubectl
    mode: '0755'

- name: Ensure kubectl binary is executable
  file:
    path: /usr/local/bin/kubectl
    mode: '0755'
  
- name: Verify kubectl installation
  command: /usr/local/bin/kubectl version --client
  register: kubectl_version
   
- name: print kubectl version
  debug:
    var: kubectl_version

- name: Print kubectl version
  ansible.builtin.debug:
    msg: "{{ kubectl_version.stdout }}"
