- name: Install the required dependencies
  yum:
    name: "{{ item }}"
    state: present
  loop:
    - yum-utils
    - device-mapper-persistent-data
    - lvm2
    - container-selinux
    - fuse-overlayfs
    - slirp4netns

- name: Add docker repository
  yum_repository:
    name: "docker"
    description: "Add Docker repository."
    baseurl: "https://download.docker.com/linux/centos/7/x86_64/stable/"
    gpgcheck: yes
    enabled: yes
    gpgkey: "https://download.docker.com/linux/centos/gpg"

- name: Install Docker
  yum:
    name: docker-ce
    state: present

- name: Start and enable Docker at boot time
  service:
    name: docker
    state: started
    enabled: yes

- name: Add ec2 user to Docker group
  user:
    name: ec2-user
    group: docker
    append: yes
