- name: Install the docker dependencies
  yum:
   name: "{{ items  }}"
   state: present
  loop:
   - yum-utils
   - device-mapper-persistent-data
   - lvm2


- name: Add docker repository
  yum_repository:
    name: "docker"
    description: "add docker repositroy.:"
    baseurl: "https://download.docker.com/linux/centos/7/x86_64/stable/"

- name:
  rpm_key:
    state: present
    key: "https://download.docker.com/linux/centos/gpg"

- name: Install docker 
  yum:
   name: docker-ce 
   state: present

- name: start and enable docker at the boot time
  service:
    name: docker
    state: started
    enabled: yes

- name: add ec2 user to docker group
  user:
   name: ec2-user
   group: docker
   append: yes


  
