-
 name: Install Docker, Jenkins, and SonarQube
 hosts: localhost
 roles:
  - Docker
  - Jenkins
  - sonarqube
  - argocd
  - prometheus_grafana
  - Update_config

#- name: Set up EKS cluster and install ArgoCD, Prometheus, Grafana
#  hosts: localhost 
#  remote_user: ram
#  roles:
#   - argocd
#   - prometheus_grafana
#   - Update_co/nfig
