plugin: aws_ec2
regions:
  - "us-east-1"
filters:
  tag:Name: Jenkins_server
  # All instances with their state as `running`
  instance-state-name: running
keyed_groups:
  -  prefix: tag
     key: tags.Name  # Group instances by their 'Name' tag
compose:
# Use the public IP address to connect to the host
  ansible_host: public_ip_address
